version: '3'
services:
  reactiko:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "7070:3000"
    volumes:
      - .:/app
  testsiko:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
    command: ["npm", "run", "test"]

